apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: microservices
type: Opaque
data:
  # echo -n 'your-secure-jwt-secret-key' | base64
  JWT_SECRET: eW91ci1zZWN1cmUtand0LXNlY3JldC1rZXk=
